name: EC2 deploy from docker

on:
  push:
    branches: ["QA"]
  pull_request:
    branches: ["main"]

jobs:
  login-and-pull-QA:
    if: github.ref == 'refs/heads/QA'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/qa:latest .
          docker push ${{ secrets.DOCKERUSERNAME }}/qa:latest

  login-and-pull-PRD:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/prd:latest .
          docker push ${{ secrets.DOCKERUSERNAME }}/prd:latest
 
  ssh-connect-ec2_QA_01:
    if: github.ref == 'refs/heads/QA'
    needs: [login-and-pull-QA]
    uses: ./.github/workflows/setup_docker_qa.yml
    secrets:
      ec2_ip: ${{ secrets.EC2_QA_1 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKERUSERNAME }}

  ssh-connect-ec2_QA_02:
    if: github.ref == 'refs/heads/QA'
    needs: [login-and-pull-QA]
    uses: ./.github/workflows/setup_docker_qa.yml
    secrets:
      ec2_ip: ${{ secrets.EC2_QA_2 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKERUSERNAME }}

  ssh-connect-ec2_PRD_01:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' 
    needs: [login-and-pull-PRD]
    uses: ./.github/workflows/setup_docker_prd.yml
    secrets:
      ec2_ip: ${{ secrets.EC2_PRD_1 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKERUSERNAME }}
 
  ssh-connect-ec2_PRD_02:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' 
    needs: [login-and-pull-PRD]
    uses: ./.github/workflows/setup_docker_prd.yml
    secrets:
      ec2_ip: ${{ secrets.EC2_PRD_2 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKERUSERNAME }}
  
  ssh-connect-ec2_PRD_03:
    if:  github.event_name == 'pull_request' && github.base_ref == 'main' 
    needs: [login-and-pull-PRD]
    uses: ./.github/workflows/setup_docker_prd.yml
    secrets:
      ec2_ip: ${{ secrets.EC2_PRD_3 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKERUSERNAME }}
   
  ssh-connect-ec2_PRD_04:
    if:  github.event_name == 'pull_request' && github.base_ref == 'main' 
    needs: [login-and-pull-PRD]
    uses: ./.github/workflows/setup_docker_prd.yml
    secrets:
      ec2_ip: ${{ secrets.EC2_PRD_4 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKERUSERNAME }}
  